import type { Metadata } from "next";
import Link from "next/link";
import { site } from "@/lib/site";

/**
 * Product-scoped terms of use for the Insights mobile app.
 * Companion document to `./privacy/page.tsx`.
 */

const app = site.apps.insights;

export const metadata: Metadata = {
  title: `Terms of Use · ${app.name}`,
  description: `Terms that apply to your use of the ${app.name} mobile app.`,
  alternates: { canonical: app.paths.terms },
  robots: { index: true, follow: true },
};

export default function InsightsTermsPage() {
  return (
    <div className="px-5 py-16 sm:px-6 lg:py-24">
      <article className="mx-auto max-w-3xl text-sm leading-7 text-muted">
        <p className="text-xs font-semibold uppercase tracking-[0.18em] text-accent">
          {app.name}
        </p>
        <h1 className="mt-3 text-4xl font-semibold tracking-tight text-ink">
          Terms of Use
        </h1>
        <p className="mt-4 text-xs uppercase tracking-[0.12em]">
          Last updated {app.policiesLastUpdated}
        </p>

        <div className="mt-8 space-y-5">
          <p>
            These terms (the &ldquo;<strong>Terms</strong>&rdquo;) apply to
            your use of the <strong>{app.name}</strong> mobile app,
            published by <strong>Enhancify</strong>
            {" "}(&ldquo;<strong>we</strong>&rdquo;,
            &ldquo;<strong>us</strong>&rdquo;), based in {site.country}. By
            installing or using the app you agree to these Terms. If you do
            not agree, please stop using the app.
          </p>

          <h2 className="text-lg font-semibold text-ink">The service</h2>
          <p>
            {app.name} is a news reader. We aggregate publicly available
            news stories from third-party providers and present short
            AI-generated summaries alongside the original headlines. We do
            not employ the journalists who write these stories, and we do
            not endorse the views expressed in them.
          </p>

          <h2 className="text-lg font-semibold text-ink">Accounts</h2>
          <p>
            You may use the app anonymously or with an account (Google
            Sign-in or email/password). You are responsible for keeping
            your credentials secure. We may suspend or terminate an
            account that abuses the service or violates these Terms. You
            may request deletion of your account and associated data at
            any time. See {" "}
            <Link
              href={app.paths.deleteAccount}
              className="text-ink underline"
            >
              Delete your account
            </Link>
            . Our data-handling practices are described in the {" "}
            <Link
              href={app.paths.privacy}
              className="text-ink underline"
            >
              Privacy Policy
            </Link>
            .
          </p>

          <h2 className="text-lg font-semibold text-ink">Acceptable use</h2>
          <p>You agree not to:</p>
          <ul className="list-disc space-y-2 pl-5">
            <li>
              Attempt to reverse engineer, decompile, or extract source
              code from the app beyond rights granted by applicable law.
            </li>
            <li>
              Interfere with, probe, or disrupt our backend services, or
              circumvent rate limits, authentication, or Firestore security
              rules.
            </li>
            <li>
              Scrape the app or its APIs, or resell content served by the
              app.
            </li>
            <li>
              Use the app to break the law or infringe anyone&rsquo;s
              rights (including intellectual-property and privacy rights).
            </li>
            <li>Impersonate anyone or provide false information when signing up.</li>
          </ul>

          <h2 className="text-lg font-semibold text-ink">News content</h2>
          <p>
            Story titles, images, and full-article URLs come from
            third-party news providers and remain the property of their
            respective owners. Our short AI-generated summaries are
            provided for convenience and reflect the source article at the
            moment of ingestion. They may be inaccurate, out of date, or
            miss context. Always click through to the original publisher
            for the authoritative version of a story.
          </p>
          <p>
            We do not guarantee the accuracy, completeness, timeliness, or
            fitness-for-purpose of any news content displayed in the app.
            Nothing in {app.name} is financial, legal, medical, or
            professional advice.
          </p>

          <h2 className="text-lg font-semibold text-ink">AI-generated images</h2>
          <p>
            Some stories are illustrated by images generated by an AI
            model from the story&rsquo;s headline and summary. These
            images are illustrative, are not photographs of actual events,
            and should not be interpreted as depicting real people,
            places, or events.
          </p>

          <h2 className="text-lg font-semibold text-ink">Notifications</h2>
          <p>
            If you enable push notifications, we may send you alerts about
            selected news stories. You can disable them at any time from
            your device&rsquo;s notification settings.
          </p>

          <h2 className="text-lg font-semibold text-ink">Availability</h2>
          <p>
            We provide the app on an &ldquo;<strong>as is</strong>&rdquo;
            and &ldquo;<strong>as available</strong>&rdquo; basis, without
            warranties of any kind, express or implied. We may modify,
            suspend, or discontinue the service or any feature at any time,
            with or without notice.
          </p>

          <h2 className="text-lg font-semibold text-ink">Liability</h2>
          <p>
            To the fullest extent allowed by applicable law, Enhancify is
            not liable for indirect, incidental, special, consequential,
            or punitive damages, or any loss of profits, data, or goodwill,
            arising out of or in connection with your use of {app.name}.
            Our aggregate liability for any claim shall not exceed the
            amount you paid us to use the app in the twelve months
            preceding the claim (which is presently zero, as the app is
            free to use).
          </p>

          <h2 className="text-lg font-semibold text-ink">Third-party services</h2>
          <p>
            The app relies on Google Firebase and Google Play Services and
            may open URLs handled by your device&rsquo;s browser or other
            apps. Your interactions with those services are governed by
            their respective terms.
          </p>

          <h2 className="text-lg font-semibold text-ink">Changes</h2>
          <p>
            We may update these Terms from time to time. Material changes
            will be reflected by updating the &ldquo;Last updated&rdquo;
            date above. Your continued use of the app after such changes
            constitutes acceptance of the revised Terms.
          </p>

          <h2 className="text-lg font-semibold text-ink">Governing law</h2>
          <p>
            These Terms are governed by the laws of {site.country}. Courts
            in {site.country} have exclusive jurisdiction over any dispute
            arising out of or in connection with these Terms, subject to
            applicable law.
          </p>

          <h2 className="text-lg font-semibold text-ink">Contact</h2>
          <p>
            {app.name}, published by Enhancify
            <br />
            Email: {" "}
            <a className="text-ink underline" href={`mailto:${app.contactEmail}`}>
              {app.contactEmail}
            </a>
            <br />
            Website: {" "}
            <a className="text-ink underline" href={site.url}>
              {site.url.replace(/^https?:\/\//, "")}
            </a>
          </p>

          <p>
            See also {" "}
            <Link
              href={app.paths.privacy}
              className="text-ink underline"
            >
              Privacy Policy
            </Link>
            .
          </p>
        </div>
      </article>
    </div>
  );
}
